CREATE TABLE IF NOT EXISTS empresa 
(
	codigo serial NOT NULL,
	designacao VARCHAR(250) NULL DEFAULT NULL,
	email VARCHAR(250) NULL DEFAULT NULL,
	endereco VARCHAR(250) NULL DEFAULT NULL,
	telefone VARCHAR(250) NULL DEFAULT NULL,
	fax VARCHAR(250) NULL DEFAULT NULL,
	website VARCHAR(250) NULL DEFAULT NULL,
	nif VARCHAR(250) NULL DEFAULT NULL,
	logotipo_url VARCHAR(500) NULL DEFAULT NULL,
	enabled BIT(1) NOT NULL DEFAULT b'1',
	CONSTRAINT empresa_pkey PRIMARY KEY (codigo)
);